language: ruby
rvm:
  - 2.4.1

install:
  - bundle install
  - gem install jekyll

branches:
  only:
    - master

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
    recipients:
      - david@okun.io
    on_success: always
    on_failure: always

script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh

after_success:
  - chmod +x _scripts/deploy.sh
  - _scripts/deploy.sh

sudo: true
addons:
  apt:
    packages:
      - ncftp
