# Site settings
title: David Okun
header-img: img/home-bg.jpg
email: david@okun.io
copyright_name: David Okun
description: Constantly Trying New Stuff For You
baseurl: ""
url: "https://david.okun.io"
twitter_username: dokun24
github_username:  dokun1
instagram_username: dokun1
email_username:  david@okun.io
linkedin_username: david-okun
stack_overflow_username: 1604167/dokun1
collections:
  speaking:
    output: true



# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json", "package-lock.json","README.md"]

plugins: [jekyll-paginate]
